-- CreateTable
CREATE TABLE `GIANGVIEN` (
    `maGV` VARCHAR(10) NOT NULL,
    `hoTen` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `khoaBoMon` VARCHAR(100) NULL,

    UNIQUE INDEX `GIANGVIEN_email_key`(`email`),
    PRIMARY KEY (`maGV`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TAIKHOAN` (
    `maTK` INTEGER NOT NULL AUTO_INCREMENT,
    `tenDangNhap` VARCHAR(50) NOT NULL,
    `matKhau` VARCHAR(255) NOT NULL,
    `vaiTro` VARCHAR(20) NOT NULL,
    `trangThai` INTEGER NOT NULL DEFAULT 1,
    `maGV` VARCHAR(10) NULL,

    UNIQUE INDEX `TAIKHOAN_tenDangNhap_key`(`tenDangNhap`),
    UNIQUE INDEX `TAIKHOAN_maGV_key`(`maGV`),
    PRIMARY KEY (`maTK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MONHOC` (
    `maMon` VARCHAR(10) NOT NULL,
    `tenMon` VARCHAR(150) NOT NULL,
    `soTinChi` INTEGER NOT NULL,

    PRIMARY KEY (`maMon`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DOKHO` (
    `maDoKho` INTEGER NOT NULL AUTO_INCREMENT,
    `tenDoKho` VARCHAR(30) NOT NULL,

    UNIQUE INDEX `DOKHO_tenDoKho_key`(`tenDoKho`),
    PRIMARY KEY (`maDoKho`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CAUHOI` (
    `maCauHoi` INTEGER NOT NULL AUTO_INCREMENT,
    `noiDung` TEXT NOT NULL,
    `ngayTao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `maMon` VARCHAR(10) NOT NULL,
    `maDoKho` INTEGER NOT NULL,
    `maGV` VARCHAR(10) NOT NULL,

    PRIMARY KEY (`maCauHoi`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DETHI` (
    `maDeThi` INTEGER NOT NULL AUTO_INCREMENT,
    `hocKy` TINYINT NOT NULL,
    `namHoc` VARCHAR(9) NOT NULL,
    `thoiLuong` INTEGER NOT NULL,
    `ngayTao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `maMon` VARCHAR(10) NOT NULL,
    `maGV` VARCHAR(10) NOT NULL,

    PRIMARY KEY (`maDeThi`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHITIETDETHI` (
    `maDeThi` INTEGER NOT NULL,
    `maCauHoi` INTEGER NOT NULL,
    `soCau` TINYINT NOT NULL,

    PRIMARY KEY (`maDeThi`, `maCauHoi`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LOPHOC` (
    `maLop` VARCHAR(10) NOT NULL,
    `tenLop` VARCHAR(100) NOT NULL,
    `maMon` VARCHAR(10) NOT NULL,

    PRIMARY KEY (`maLop`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SINHVIEN` (
    `maSV` VARCHAR(10) NOT NULL,
    `hoTen` VARCHAR(100) NOT NULL,
    `maLop` VARCHAR(10) NOT NULL,

    PRIMARY KEY (`maSV`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BANGDIEM` (
    `maBangDiem` INTEGER NOT NULL AUTO_INCREMENT,
    `hocKy` TINYINT NOT NULL,
    `namHoc` VARCHAR(9) NOT NULL,
    `diemSo` DECIMAL(4, 1) NOT NULL,
    `ghiChu` VARCHAR(255) NULL,
    `maSV` VARCHAR(10) NOT NULL,
    `maLop` VARCHAR(10) NOT NULL,
    `maDeThi` INTEGER NOT NULL,

    PRIMARY KEY (`maBangDiem`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `QUYDINH` (
    `maQuyDinh` INTEGER NOT NULL AUTO_INCREMENT,
    `tenThamSo` VARCHAR(50) NOT NULL,
    `giaTri` VARCHAR(50) NOT NULL,
    `moTa` VARCHAR(255) NULL,
    `ngayCapNhat` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `maTKCapNhat` INTEGER NOT NULL,

    UNIQUE INDEX `QUYDINH_tenThamSo_key`(`tenThamSo`),
    PRIMARY KEY (`maQuyDinh`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TAIKHOAN` ADD CONSTRAINT `TAIKHOAN_maGV_fkey` FOREIGN KEY (`maGV`) REFERENCES `GIANGVIEN`(`maGV`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CAUHOI` ADD CONSTRAINT `CAUHOI_maMon_fkey` FOREIGN KEY (`maMon`) REFERENCES `MONHOC`(`maMon`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CAUHOI` ADD CONSTRAINT `CAUHOI_maDoKho_fkey` FOREIGN KEY (`maDoKho`) REFERENCES `DOKHO`(`maDoKho`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CAUHOI` ADD CONSTRAINT `CAUHOI_maGV_fkey` FOREIGN KEY (`maGV`) REFERENCES `GIANGVIEN`(`maGV`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETHI` ADD CONSTRAINT `DETHI_maMon_fkey` FOREIGN KEY (`maMon`) REFERENCES `MONHOC`(`maMon`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DETHI` ADD CONSTRAINT `DETHI_maGV_fkey` FOREIGN KEY (`maGV`) REFERENCES `GIANGVIEN`(`maGV`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHITIETDETHI` ADD CONSTRAINT `CHITIETDETHI_maDeThi_fkey` FOREIGN KEY (`maDeThi`) REFERENCES `DETHI`(`maDeThi`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHITIETDETHI` ADD CONSTRAINT `CHITIETDETHI_maCauHoi_fkey` FOREIGN KEY (`maCauHoi`) REFERENCES `CAUHOI`(`maCauHoi`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `LOPHOC` ADD CONSTRAINT `LOPHOC_maMon_fkey` FOREIGN KEY (`maMon`) REFERENCES `MONHOC`(`maMon`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SINHVIEN` ADD CONSTRAINT `SINHVIEN_maLop_fkey` FOREIGN KEY (`maLop`) REFERENCES `LOPHOC`(`maLop`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BANGDIEM` ADD CONSTRAINT `BANGDIEM_maSV_fkey` FOREIGN KEY (`maSV`) REFERENCES `SINHVIEN`(`maSV`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BANGDIEM` ADD CONSTRAINT `BANGDIEM_maLop_fkey` FOREIGN KEY (`maLop`) REFERENCES `LOPHOC`(`maLop`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BANGDIEM` ADD CONSTRAINT `BANGDIEM_maDeThi_fkey` FOREIGN KEY (`maDeThi`) REFERENCES `DETHI`(`maDeThi`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `QUYDINH` ADD CONSTRAINT `QUYDINH_maTKCapNhat_fkey` FOREIGN KEY (`maTKCapNhat`) REFERENCES `TAIKHOAN`(`maTK`) ON DELETE RESTRICT ON UPDATE CASCADE;
